/**
 * extract-cookies.js
 * Reads YouTube cookies directly from Chrome's cookie DB (unencrypted v10- ones)
 * Run: node scripts/extract-cookies.js
 * Then copy cookies.txt content into Railway YOUTUBE_COOKIES env var
 */

const path = require('path');
const fs = require('fs');
const os = require('os');

// Chrome cookie DB path on Windows
const chromeCookiePath = path.join(
  os.homedir(),
  'AppData', 'Local', 'Google', 'Chrome', 'User Data', 'Default', 'Network', 'Cookies'
);

const altPath = path.join(
  os.homedir(),
  'AppData', 'Local', 'Google', 'Chrome', 'User Data', 'Default', 'Cookies'
);

const cookiePath = fs.existsSync(chromeCookiePath) ? chromeCookiePath : altPath;

if (!fs.existsSync(cookiePath)) {
  console.error('❌ Chrome cookie file not found at:', cookiePath);
  process.exit(1);
}

// Copy to temp (Chrome locks the original)
const tmpPath = path.join(os.tmpdir(), 'chrome_cookies_tmp.db');
fs.copyFileSync(cookiePath, tmpPath);

try {
  const Database = require('better-sqlite3');
  const db = new Database(tmpPath, { readonly: true });

  const rows = db.prepare(`
    SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
    FROM cookies
    WHERE host_key LIKE '%youtube.com' OR host_key LIKE '%google.com'
    ORDER BY host_key
  `).all();

  db.close();

  if (!rows.length) {
    console.error('❌ No YouTube/Google cookies found. Make sure you are logged in to YouTube in Chrome.');
    process.exit(1);
  }

  // Convert to Netscape format
  const lines = ['# Netscape HTTP Cookie File', '# Generated by extract-cookies.js', ''];

  for (const r of rows) {
    // Chrome stores expiry as microseconds since 1601-01-01
    // Convert to Unix timestamp
    let expires = 0;
    if (r.expires_utc) {
      expires = Math.floor((r.expires_utc / 1000000) - 11644473600);
      if (expires < 0) expires = 0;
    }

    const host = r.host_key.startsWith('.') ? r.host_key : '.' + r.host_key;
    const includeSubdomains = host.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = r.is_secure ? 'TRUE' : 'FALSE';

    // Note: encrypted cookies will have empty value — that's OK,
    // unencrypted session cookies (value field not empty) still work
    if (r.value) {
      lines.push(`${host}\t${includeSubdomains}\t${r.path}\t${secure}\t${expires}\t${r.name}\t${r.value}`);
    }
  }

  const output = lines.join('\n');
  const outPath = path.join(__dirname, '..', 'cookies.txt');
  fs.writeFileSync(outPath, output, 'utf-8');

  console.log(`✅ Exported ${rows.filter(r => r.value).length} cookies to cookies.txt`);
  console.log(`📁 File: ${outPath}`);
  console.log('');
  console.log('Next steps:');
  console.log('1. Copy the contents of cookies.txt');
  console.log('2. Go to Railway → Variables → Add YOUTUBE_COOKIES → paste contents');

} catch (e) {
  console.error('❌ Error reading cookies:', e.message);
  console.error('Chrome may be encrypting all cookies with DPAPI.');
  console.error('');
  console.error('Alternative: Use the "Get cookies.txt LOCALLY" Chrome extension:');
  console.error('https://chromewebstore.google.com/search/get%20cookies.txt');
} finally {
  try { fs.unlinkSync(tmpPath); } catch {}
}
